### ISSUE TITLE
Computer running Windows 10 (20H2) or newer

### ISSUE THREAD

**Issue by TiberiumFusion** [RealParSec/sparkizx.github.io#3]
> Requirments
> Computer running Windows 10 (20H2) or newer

What are the steps in this guide that unavoidably fail when attempted on other versions of Windows? This `requirment` seems arbitrary. None of the [publicly listed changes](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-20h2) seem even remotely relevant to Hammer++, but Ficool2 himself links to this guide, so there must be something important in there. For improving compatibility, it would be helpful to know the critical ability that 11 and 20H2 have but 2004-1507, 8.1, and 7 all lack.

**Comment by RealParSec** [comment]
Think of it like this, this is the version I was running at the time I actually added this information and I know it works at least on that version of Windows. But you are right, this is why it got changed, it should make it clear now.
